name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    # Definindo variáveis globais para este Job
    env:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: root
      DB_PORT: 5432
    
    strategy:
      matrix:
        # Sugestão: Use versões mais recentes se possível (ex: 1.21)
        go_version: ['1.18', '1.17', '1.21'] 
        os: ['ubuntu-latest'] # ubuntu-18.04 está entrando em desuso

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build-DB
      run: docker-compose build
      
    - name: Create-DB
      run: docker-compose up -d

    - name: Test
      # O teste agora terá as variáveis de ambiente disponíveis para o database.go
      run: go test -v main_test.go 
      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
